name: Demo
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: print steps
          run: |
            echo "hello world 1 !"
            echo "hello world 2 !"